#pragma once
#ifndef _LIB_SIMPLE_PLAYER_ERROR_DEFINE_H
#define _LIB_SIMPLE_PLAYER_ERROR_DEFINE_H

#define LIB_SIMPLE_PLAYER_OK                0
#define LIB_SIMPLE_PLAYER_UNDEFINED_ERROR   -1
#define LIB_SIMPLE_PLAYER_NO_MEMORY         -2
#define LIB_SIMPLE_PLAYER_BAD_PARAMETER     -3
#define LIB_SIMPLE_PLAYER_INVALID_HANDLE    -4
#define LIB_SIMPLE_PLAYER_ALREADY_PLAYING   -5

#endif // !_LIB_SIMPLE_PLAYER_ERROR_DEFINE_H
